### ISSUE TITLE
IndyObjectHandler throws error when scope object is a lambda

### ISSUE THREAD

**Issue by michaelhixson** [spullara/mustache.java#143]
When I use `IndyObjectHandler` as the object handler for my `DefaultMustacheFactory`, I get an error when one of the scope objects is a lambda.

I can't provide the full source code, but here is the basic gist:

```
DefaultMustacheFactory factory = ...
factory.setObjectHandler(new IndyObjectHandler());
Mustache template = factory.compile(filename);
Object viewObject = ...
// This is the problematic scope object.  I declare it using a method reference.
// If I declare it with an anonymous inner class, the error goes away.
MyFunctionalInterface scopeAdditions = someClass::someMethod;
// This is the line that throws the error.  See the sample stack trace below.
template.execute(writer, new Object[] { viewObject, scopeAdditions });
```

Here is how the stack trace looks, with some project-specific class names / filenames removed:

```
Caused by: com.github.mustachejava.MustacheException: null @[((redacted template filename)):12]
	at com.github.mustachejava.codes.DefaultCode.get(DefaultCode.java:144) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:40) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:32) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:161) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.PartialCode.execute(PartialCode.java:62) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:32) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:161) ~[compiler-0.9.0.jar:na]
	((redacted lines from my application and framework))
	... 20 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at com.github.mustachejava.codegen.GuardCompiler.compile(GuardCompiler.java:85) ~[codegen-0.9.0.jar:na]
	at com.github.mustachejava.codegen.GuardCompiler.compile(GuardCompiler.java:34) ~[codegen-0.9.0.jar:na]
	at com.github.mustachejava.codegen.CodegenReflectionWrapper.<init>(CodegenReflectionWrapper.java:17) ~[codegen-0.9.0.jar:na]
	at com.github.mustachejava.codegen.CodegenObjectHandler.createWrapper(CodegenObjectHandler.java:56) ~[codegen-0.9.0.jar:na]
	at com.github.mustachejava.reflect.ReflectionObjectHandler.findWrapper(ReflectionObjectHandler.java:141) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.reflect.ReflectionObjectHandler.find(ReflectionObjectHandler.java:66) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.indy.IndyObjectHandler.find(IndyObjectHandler.java:16) ~[indy-0.9.0.jar:na]
	at com.github.mustachejava.reflect.GuardedBinding.getWrapper(GuardedBinding.java:94) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.reflect.GuardedBinding.createAndGet(GuardedBinding.java:79) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.reflect.GuardedBinding.get(GuardedBinding.java:74) ~[compiler-0.9.0.jar:na]
	at com.github.mustachejava.codes.DefaultCode.get(DefaultCode.java:139) ~[compiler-0.9.0.jar:na]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: ((redacted class name))$$Lambda$179/2139129759
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_45]
	at com.github.mustachejava.codegen.CompiledGuards44.<clinit>(compiledguards:3) ~[na:na]
	... 48 common frames omitted
```

Is this kind of error expected?  I might be using the indy module outside of its intended use case.

**Comment by spullara** [comment]
Is there a cool use case for this?

**Comment by michaelhixson** [comment]
Not sure if it's cool, but I am actually doing this.  The `MyFunctionalInterface` contains a method that would be cumbersome to implement in the view objects themselves.  It is easier to inject that dependency at the writer level once than individually in every view.  And because I'm only adding one method, it was natural to write it as a functional interface / lambda.

I'm not actually using `IndyObjectHandler`, and if I was then I could easily not use a lambda.  So if you're asking me what I think the priority of this issue is, I'd say it's very low.

**Comment by spullara** [comment]
I'm actually going to remove codegen/indy as they don't have any significant speedup and are painful to maintain.
